services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    env_file:
      - ./proxy/.env
    environment:
      - INCIDENTS_FILE_PATH=/data/incidents.json
    ports:
      - "3001:3001"
    volumes:
      - ./proxy/incidents.json:/data/incidents.json:ro
    restart: unless-stopped